from ADN import Rosa_ADN

testName = "ADNrosalind"
h=">{0}".format(testName)
seq="AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
iRosa_ADN = Rosa_ADN(h, seq)
result = iRosa_ADN.ADNcount()
exp_str = "20 12 17 21"
if result == exp_str :
    print(".\n")
else :
    print("error at {0} : {1}\n".format(testName, result))
    
testName = "ADNrosalind_other"
h=">{0}".format(testName)
seq="AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAGAGTGTCTGATAGCAGC"
iRosa_ADN = Rosa_ADN(h, seq)
result = iRosa_ADN.ADNcount()
exp_str = "17 12 17 21"
if result == exp_str :
    print(".\n")
else :
    print("error at {0} : {1}\n".format(testName, result))
    
    
#===============================================================================
# testName = "ADNrosalind_Result"
# h=">{0}".format(testName)
# seq="CCGCTGGAAGGGGGGCTTTTCCTAGGACGGCCCGCGTTCCAAGATTAAGCGACACACATTTCGAACTCTCGCACACTATCCGATTTGACCTGGACTTACTTGTTCAGTATTTCCGTTCAGGTGTAAAATGATGTACGTTCTCTTAAGGTAGGCGAACTGTTCTATGATCCCAGTATAGTCCCTACTTTAGATAGTGAAGAGCATCTCGTCTCACCTAGTAGGCGACATTAGTGTGATTGAGTACCAGCGGTTAAGTGCCATCCGTACATGAGACTGTTTGCTAGAGCCCAGATTATCACGCAACCTTGCTTCTTCGGGACACGCTGCCCGTACTCGGACTGCGGGCATTGACAGCATCAGTCACCTCCGCAGTTTCTGTCGAAGCGTCATCCCCTAGGAAATAAACGCCGACTAATGCTAGAGACTACAAGAATGGGTCTACGCGCTGTCAGGACAGGACGAGGCGGCCCACGTCTGTGTCGACATGCATGGAGTAACATTCGGTCCCCATAATGGGTCTTGATTACGCTGCCCTTGGCAGAAATCTTAAAAGTATCGGAGAGCAATTATTACTAATGACGAACTATCGATCCGTATTTCAGGTATCTGAACTCTTGTTCTCTTAAGCTTACTCTCACACACCCGATTAGGTGTAATCGCCTCATGCGATTTGATTATTTTGCATTTCTAGTCGTAGCGACAGGGCTGCCGCGGTTACGGCGGTTTGAAGGCAGTGCAAAAACCGCTCAAACCTGTCTTCAAGCGTACACGCCAGATGAGTACTATATTCGATAGCGGTGCGAGAGATGTCCGCCTTCCCTCTGA"
# iRosa_ADN = Rosa_ADN(h, seq)
# result = iRosa_ADN.ADNcount()
# print("{0} : {1}\n".format(testName, result))
#     
#===============================================================================